export const commercialServices = [
  {
    category: 'Commercial',
    slug: 'hotel-airbnb-cleaning',
    title: 'Hotel & Airbnb Continuous Cleaning',
    shortTitle: 'Hotel & Airbnb cleaning',
    price: 'From £20/hr (min. 5 hrs)',
    tagline: 'Ongoing turnover cleaning, not a one-off visit',
    description: 'Continuous housekeeping for hotels, Airbnb and serviced apartments — built for back-to-back guest turnovers rather than a single clean. We can also run full housekeeping for an entire hotel.',
    includes: ['Guest changeover / turnover cleaning', 'Fresh linen and bed making', 'Bathroom sanitising between stays', 'Kitchen and communal area reset', 'Full hotel housekeeping contracts available', 'Flexible early-checkout and same-day slots'],
  },
  {
    category: 'Commercial',
    slug: 'recurring-contract-cleaning',
    title: 'Recurring & Contract Cleaning',
    shortTitle: 'Recurring cleaning',
    price: 'From £20/hr',
    tagline: 'Ongoing cleaning on a schedule that suits your business',
    description: 'Daily, weekly or fortnightly contract cleaning for any business that wants consistent standards without booking a one-off visit each time.',
    includes: ['Daily, weekly or fortnightly visits', 'Same team assigned where possible', 'Scheduled around your opening hours', 'Consistent standards, checked regularly', 'Flexible contract length', 'Key holding available'],
  },
  {
    category: 'Commercial',
    slug: 'office-cleaning',
    title: 'Office Cleaning',
    shortTitle: 'Office cleaning',
    price: 'From £21.50/hr',
    tagline: 'A cleaner office with less disruption',
    description: 'Professional office cleaning around your working hours, suitable for small offices, studios and larger workplaces.',
    includes: ['Desks and workstations sanitised', 'Kitchen and breakroom cleaning', 'Washroom hygiene', 'Reception and common areas', 'Bins and recycling', 'Floors vacuumed and mopped'],
  },
  {
    category: 'Commercial',
    slug: 'retail-cleaning',
    title: 'Retail Cleaning',
    shortTitle: 'Retail cleaning',
    price: 'From £20/hr',
    tagline: 'Keep your store ready for customers',
    description: 'Cleaning for shops, salons, showrooms and retail spaces, scheduled around opening hours.',
    includes: ['Sales floor cleaning', 'Fitting rooms cleaned', 'Display glass wiped', 'Counters sanitised', 'Staff areas cleaned', 'Entrances maintained'],
  },
  {
    category: 'Commercial',
    slug: 'restaurant-hospitality-cleaning',
    title: 'Restaurant & Hospitality Cleaning',
    shortTitle: 'Restaurant & hospitality',
    price: 'From £20/hr',
    tagline: 'Food-safe cleaning for busy venues',
    description: 'Specialist cleaning for restaurants, cafes, bars and hospitality spaces where hygiene and presentation matter.',
    includes: ['Kitchen deep cleaning', 'Dining area sanitising', 'Bar and counter cleaning', 'Floor scrubbing', 'Grease and build-up removal', 'Inspection-ready hygiene focus'],
  },
  {
    category: 'Commercial',
    slug: 'gym-fitness-cleaning',
    title: 'Gym & Fitness Cleaning',
    shortTitle: 'Gym & fitness',
    price: 'From £20/hr',
    tagline: 'Clean, fresh fitness spaces',
    description: 'High-touch cleaning for gyms, studios, changing rooms and fitness facilities.',
    includes: ['Equipment wiped and disinfected', 'Changing rooms cleaned', 'Showers and toilets sanitised', 'Studio floors cleaned', 'Reception areas maintained', 'High-touch surface focus'],
  },
  {
    category: 'Commercial',
    slug: 'school-education-cleaning',
    title: 'School & Education Cleaning',
    shortTitle: 'School & education',
    price: 'From £20/hr',
    tagline: 'Safe spaces for learning',
    description: 'Cleaning for classrooms, nurseries, colleges and education facilities using suitable products and careful routines.',
    includes: ['Classrooms cleaned', 'Corridors and stairs', 'Toilet blocks sanitised', 'Canteen areas cleaned', 'Sports halls cleaned', 'Child-safe product options'],
  },
  {
    category: 'Commercial',
    slug: 'warehouse-industrial-cleaning',
    title: 'Warehouse & Industrial Cleaning',
    shortTitle: 'Warehouse & industrial',
    price: 'From £20/hr',
    tagline: 'Heavy-duty cleaning for large sites',
    description: 'Cleaning for warehouses, industrial units and facilities that need practical, robust cleaning support.',
    includes: ['Industrial floor cleaning', 'Loading bay areas', 'Welfare facilities', 'Office areas', 'Spillage response', 'Pressure washing options'],
  },
  {
    category: 'Commercial',
    slug: 'washroom-services',
    title: 'Washroom Services',
    shortTitle: 'Washroom services',
    price: 'From £20/hr',
    tagline: 'Reliable washroom hygiene',
    description: 'Cleaning and hygiene support for shared commercial washrooms and facilities.',
    includes: ['Regular sanitising', 'Fixtures polished', 'Odour control support', 'Consumables by request', 'Urinal descaling', 'Scheduled service visits'],
  },
  {
    category: 'Commercial',
    slug: 'medical-healthcare-cleaning',
    title: 'Medical & Healthcare Cleaning',
    shortTitle: 'Medical & healthcare',
    price: 'From £20/hr',
    tagline: 'Careful infection-control cleaning',
    description: 'Cleaning for clinics, dental practices, care settings and healthcare reception areas with a hygiene-led approach.',
    includes: ['Clinical surface cleaning', 'Waiting rooms cleaned', 'Reception hygiene', 'Consulting rooms cleaned', 'High-touch disinfection', 'Waste protocol support'],
  },
];

export const allServices = [...commercialServices];

export function getServiceBySlug(slug) {
  return allServices.find(service => service.slug === slug);
}
