export const domesticServices = [
  {
    category: 'Domestic',
    slug: 'regular-home-cleaning',
    title: 'Regular Home Cleaning',
    shortTitle: 'Regular cleaning',
    price: 'From £17/hr',
    tagline: 'Keep your home consistently spotless',
    description: 'Reliable weekly, fortnightly or monthly cleaning for busy homes. We focus on the rooms you use every day and keep standards consistent.',
    includes: ['Surfaces dusted and wiped', 'Kitchen worktops, sink and hob cleaned', 'Bathroom cleaned and sanitised', 'Vacuuming throughout', 'Hard floors mopped', 'Bins emptied'],
  },
  {
    category: 'Domestic',
    slug: 'deep-cleaning',
    title: 'Deep Cleaning',
    shortTitle: 'Deep cleaning',
    price: 'From £179',
    tagline: 'A thorough top-to-bottom reset',
    description: 'A detailed clean for homes that need more time and attention than a regular visit, including built-up grime and often-missed areas.',
    includes: ['Everything in a regular clean', 'Kitchen appliances cleaned', 'Cupboards and drawers wiped', 'Bathroom limescale removal', 'Skirting boards and switches wiped', 'Hard-to-reach areas cleaned'],
  },
  {
    category: 'Domestic',
    slug: 'end-of-tenancy-cleaning',
    title: 'End of Tenancy Cleaning',
    shortTitle: 'End of tenancy',
    price: 'From £179',
    tagline: 'Detailed move-out cleaning',
    description: 'A full-property clean for tenants, landlords and letting agents, prepared around common move-out checklist expectations.',
    includes: ['Full deep clean of every room', 'Oven, hob and extractor cleaning', 'Cupboards and wardrobes cleaned inside', 'Bathrooms deep sanitised', 'Interior windows cleaned', 'Wall marks checked'],
  },
  {
    category: 'Domestic',
    slug: 'move-in-move-out-cleaning',
    title: 'Move In / Move Out Cleaning',
    shortTitle: 'Move in / out',
    price: 'From £179',
    tagline: 'Start fresh or leave cleanly',
    description: 'Professional cleaning for moving day, whether you are preparing a new home or leaving a property ready for the next person.',
    includes: ['Complete property clean', 'Kitchen and bathroom deep clean', 'All surfaces sanitised', 'Floors vacuumed and mopped', 'Bins emptied and sanitised', 'Interior windows cleaned'],
  },
  {
    category: 'Domestic',
    slug: 'carpet-upholstery-cleaning',
    title: 'Carpet & Upholstery Cleaning',
    shortTitle: 'Carpet & upholstery',
    price: 'From £43/room',
    tagline: 'Refresh carpets, rugs and soft furnishings',
    description: 'Professional treatment for carpets, rugs, sofas and chairs to remove everyday dirt, stains, odours and allergens.',
    includes: ['Stain pre-treatment', 'Hot water extraction', 'Deodorising treatment', 'Fast drying', 'Rugs and sofas available', 'Fabric protection option'],
  },
  {
    category: 'Domestic',
    slug: 'mattress-cleaning',
    title: 'Mattress Cleaning',
    shortTitle: 'Mattress cleaning',
    price: 'From £23',
    tagline: 'Sleep cleaner and breathe easier',
    description: 'Steam and sanitising treatment to reduce dust, odours, allergens and everyday build-up in mattresses.',
    includes: ['Vacuum pre-treatment', 'Steam sanitising', 'Stain spot treatment', 'Deodorising spray', 'All mattress sizes', 'Allergen reduction'],
  },
  {
    category: 'Domestic',
    slug: 'ironing-laundry',
    title: 'Ironing & Laundry',
    shortTitle: 'Ironing & laundry',
    price: 'From £18/hr',
    tagline: 'Take laundry pressure off your week',
    description: 'Help with ironing, laundry and garment care, either as a standalone request or alongside a cleaning visit.',
    includes: ['Shirts, trousers and dresses', 'Bedding and towels', 'Folded or hung to preference', 'Delicate handling', 'Collection option by quote', 'Combine with cleaning'],
  },
  {
    category: 'Domestic',
    slug: 'window-cleaning',
    title: 'Window Cleaning',
    shortTitle: 'Window cleaning',
    price: 'From £29',
    tagline: 'Clearer glass and brighter rooms',
    description: 'Streak-free window cleaning for homes and apartments, including frames and sills where accessible.',
    includes: ['Interior window cleaning', 'Exterior windows where accessible', 'Frames and sills wiped', 'Streak-free finish', 'Conservatory options', 'Regular visits available'],
  },
];

export const commercialServices = [
  {
    category: 'Commercial',
    slug: 'office-cleaning',
    title: 'Office Cleaning',
    shortTitle: 'Office cleaning',
    price: 'From £21.50/hr',
    tagline: 'A cleaner office with less disruption',
    description: 'Professional office cleaning around your working hours, suitable for small offices, studios and larger workplaces.',
    includes: ['Desks and workstations sanitised', 'Kitchen and breakroom cleaning', 'Washroom hygiene', 'Reception and common areas', 'Bins and recycling', 'Floors vacuumed and mopped'],
  },
  {
    category: 'Commercial',
    slug: 'retail-cleaning',
    title: 'Retail Cleaning',
    shortTitle: 'Retail cleaning',
    price: 'From £18/hr',
    tagline: 'Keep your store ready for customers',
    description: 'Cleaning for shops, salons, showrooms and retail spaces, scheduled around opening hours.',
    includes: ['Sales floor cleaning', 'Fitting rooms cleaned', 'Display glass wiped', 'Counters sanitised', 'Staff areas cleaned', 'Entrances maintained'],
  },
  {
    category: 'Commercial',
    slug: 'restaurant-hospitality-cleaning',
    title: 'Restaurant & Hospitality Cleaning',
    shortTitle: 'Restaurant & hospitality',
    price: 'Quoted clearly',
    tagline: 'Food-safe cleaning for busy venues',
    description: 'Specialist cleaning for restaurants, cafes, bars and hospitality spaces where hygiene and presentation matter.',
    includes: ['Kitchen deep cleaning', 'Dining area sanitising', 'Bar and counter cleaning', 'Floor scrubbing', 'Grease and build-up removal', 'Inspection-ready hygiene focus'],
  },
  {
    category: 'Commercial',
    slug: 'gym-fitness-cleaning',
    title: 'Gym & Fitness Cleaning',
    shortTitle: 'Gym & fitness',
    price: 'Quoted clearly',
    tagline: 'Clean, fresh fitness spaces',
    description: 'High-touch cleaning for gyms, studios, changing rooms and fitness facilities.',
    includes: ['Equipment wiped and disinfected', 'Changing rooms cleaned', 'Showers and toilets sanitised', 'Studio floors cleaned', 'Reception areas maintained', 'High-touch surface focus'],
  },
  {
    category: 'Commercial',
    slug: 'school-education-cleaning',
    title: 'School & Education Cleaning',
    shortTitle: 'School & education',
    price: 'Quoted clearly',
    tagline: 'Safe spaces for learning',
    description: 'Cleaning for classrooms, nurseries, colleges and education facilities using suitable products and careful routines.',
    includes: ['Classrooms cleaned', 'Corridors and stairs', 'Toilet blocks sanitised', 'Canteen areas cleaned', 'Sports halls cleaned', 'Child-safe product options'],
  },
  {
    category: 'Commercial',
    slug: 'warehouse-industrial-cleaning',
    title: 'Warehouse & Industrial Cleaning',
    shortTitle: 'Warehouse & industrial',
    price: 'Quoted clearly',
    tagline: 'Heavy-duty cleaning for large sites',
    description: 'Cleaning for warehouses, industrial units and facilities that need practical, robust cleaning support.',
    includes: ['Industrial floor cleaning', 'Loading bay areas', 'Welfare facilities', 'Office areas', 'Spillage response', 'Pressure washing options'],
  },
  {
    category: 'Commercial',
    slug: 'washroom-services',
    title: 'Washroom Services',
    shortTitle: 'Washroom services',
    price: 'Quoted clearly',
    tagline: 'Reliable washroom hygiene',
    description: 'Cleaning and hygiene support for shared commercial washrooms and facilities.',
    includes: ['Regular sanitising', 'Fixtures polished', 'Odour control support', 'Consumables by request', 'Urinal descaling', 'Scheduled service visits'],
  },
  {
    category: 'Commercial',
    slug: 'medical-healthcare-cleaning',
    title: 'Medical & Healthcare Cleaning',
    shortTitle: 'Medical & healthcare',
    price: 'Quoted clearly',
    tagline: 'Careful infection-control cleaning',
    description: 'Cleaning for clinics, dental practices, care settings and healthcare reception areas with a hygiene-led approach.',
    includes: ['Clinical surface cleaning', 'Waiting rooms cleaned', 'Reception hygiene', 'Consulting rooms cleaned', 'High-touch disinfection', 'Waste protocol support'],
  },
];

export const allServices = [...domesticServices, ...commercialServices];

export function getServiceBySlug(slug) {
  return allServices.find(service => service.slug === slug);
}
